### ISSUE TITLE
Uncaught SyntaxError: Unexpected token * vendor, Uncaught ReferenceError: ko is not defined

### ISSUE THREAD

**Issue by sgentile** [BlueSpire/Weyland#19]
I have a default setup running inside Visual Studio.

I setup the post build step:

if '$(Configuration)'=='Release' (
    cd $(ProjectDir)
    weyland build
)

I set the web.config to debug=false

```
    <compilation debug="false" targetFramework="4.5"/>
```

The build shows successful in the VS console:
1>  durandal/composition
1>  durandal/events
1>  plugins/dialog
1>  plugins/history
1>  plugins/http
1>  plugins/observable
1>  plugins/router
1>  plugins/serializer
1>  plugins/widget
1>  durandal/system
1>  transitions/entrance
1>  durandal/viewEngine
1>  durandal/viewLocator
1>  Optimized build created at "C:\Projects\Durandal2013\Durandal2013\App\main-built.js".
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

I have the following reference:

```
<script type="text/javascript" src="~/App/main-built.js"></script>
```

When I run the application:
Uncaught SyntaxError: Unexpected token \* vendor:19
Uncaught ReferenceError: ko is not defined main-built.js:423

**Comment by EisenbergEffect** [comment]
Closing as this project is going into archive.
